# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1360e935d35a08dc251471b8a6c87311d51327bd808b6e66185ecd620f5f77dab880c46e61d2eda687a0201998b53ada782ba49dd714bb53679766a4a63fae8a

test:
  secret_key_base: 755c3bcdbb5edce893de77b07e1c5b18aef74314d7782cf7dc976e247aaf43f34b9370fa43af0b0008f6d9c604f4dde27905de317a9081bbb862cec6fc4d7fd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
