# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff81215b2ea08f8be22153de0e778cfa03ebebbfbd3099f39111fecd32359f8b49185f7a3c3e4b0e30b41a41e687ee82b1d38dfc765fed3f24867e2ed3d4a118

test:
  secret_key_base: 9e6ff5c8ccffdb595db6ee89112c7fa0bb139c0ce771e1cab5e8194316d80ba5466fb2acb40943662e4cb9d06fee10d0626c51618586e20293a588c57f088898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
